version: '3.9'

services:
  app:
    container_name: py-app
    build: 
      context: ./
      dockerfile: ./docker/build/python.Dockerfile
    volumes:
      - ./src:/usr/src/app
    env_file:
      - .env